name: check

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  lint:
    name: Check lint and format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Install dependencies
        run: pnpm install

      - name: Check format
        run: pnpm run format:check

      - name: Run eslint
        run: pnpm run lint:check

  typecheck:
    name: Check TS types
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Install dependencies
        run: pnpm install

      - name: Check types
        run: pnpm run typecheck

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test:run
